pins:
  - pin: 1A
    function: 12V all times
    type: 12V
  - pin: 1B
    function: ECU power in start & run
    type: 12V
  - pin: 3A
    function: Power GND
    type: pgnd
    color: white
  - pin: 3B
    function: Power GND
    type: pgnd
    color: white



info:
  image:
    file: main.jpg
  pins:
    - pin: 1A
      x: 3984
      y: 312
    - pin: 1B
      x: 3984
      y: 512
    - pin: 1C
      x: 3860
      y: 312
    - pin: 1D
      x: 3860
      y: 512
    - pin: 3A
      x: 1604
      y: 312
    - pin: 3B
      x: 1604
      y: 512
    - pin: 3C
      x: 1488
      y: 312
    - pin: 3D
      x: 1488
      y: 512
