outputs:
  GPIOD_7:  "Lowside 1"
  GPIOG_9:  "Lowside 2"
  GPIOG_10: "Lowside 3"
  GPIOG_11: "Lowside 4"
  GPIOG_12: "Lowside 5"
  GPIOG_13: "Lowside 6"
  GPIOG_14: "Lowside 7"
  GPIOB_4:  "Lowside 8"
  GPIOB_5:  "Lowside 9"
  GPIOB_6:  "Lowside 10"
  GPIOB_7:  "Lowside 11"
  GPIOB_8:  "Lowside 12"
  GPIOB_9:  "Lowside 13"
  GPIOE_0:  "Lowside 14"
  GPIOE_1:  "Lowside 15"
  GPIOE_2:  "Lowside 16"

  GPIOD_4:  "Ign 1"
  GPIOD_3:  "Ign 2"
  GPIOC_9:  "Ign 3"
  GPIOC_8:  "Ign 4"
  GPIOC_7:  "Ign 5"
  GPIOG_8:  "Ign 6"
  GPIOG_7:  "Ign 7"
  GPIOG_6:  "Ign 8"
  GPIOG_5:  "Ign 9"
  GPIOG_4:  "Ign 10"
  GPIOG_3:  "Ign 11"
  GPIOG_2:  "Ign 12"

  GPIOA_9:  "Highside 1"
  GPIOA_8:  "Highside 2"
  GPIOD_15: "Highside 3"
  GPIOD_14: "Highside 4"

event_inputs:
  GPIOC_6:  "Digital 1"
  GPIOE_11: "Digital 2"
  GPIOE_12: "Digital 3"
  GPIOE_13: "Digital 4"
  GPIOE_14: "Digital 5"
  GPIOE_15: "Digital 6"
  GPIOE_7:  "Digital 7"
  GPIOE_8:  "Digital 8"

switch_inputs:
  GPIOC_6:  "Digital 1"
  GPIOE_11: "Digital 2"
  GPIOE_12: "Digital 3"
  GPIOE_13: "Digital 4"
  GPIOE_14: "Digital 5"
  GPIOE_15: "Digital 6"
  GPIOE_7:  "Digital 7"
  GPIOE_8:  "Digital 8"

analog_inputs:
  EFI_ADC_0: "Analog Volt 5"
  EFI_ADC_1: "Analog Volt 6"
  EFI_ADC_2: "Analog Volt 7"
  EFI_ADC_3: "Analog Volt 8"
  EFI_ADC_4: "Analog Volt 9"
  EFI_ADC_5: "Analog Volt 10"
  EFI_ADC_6: "Analog Volt 11"
  EFI_ADC_7: "Analog Volt 12"
  EFI_ADC_8: "Analog Temp 3"
  EFI_ADC_9: "Analog Temp 4"
  EFI_ADC_10: "Analog Volt 1"
  EFI_ADC_11: "Analog Volt 2"
  EFI_ADC_12: "Analog Volt 3"
  EFI_ADC_13: "Analog Volt 4"
  EFI_ADC_14: "Analog Temp 1"
  EFI_ADC_15: "Analog Temp 2"
