pins:
  - pin: 2A
    id: GPIOG_7
    class: outputs
    ts_name: 2A - INJ_1
    function: Injector #1
    type: inj
    color: orange Y1

  - pin: 2B
    id: GPIOD_12
    class: outputs
    ts_name: 2B - ECF (PWM8)
    function: Engine Radiator Fan
    color: orange B4
    type: ls

  - pin: 2C
    id: GPIOD_9
    class: outputs
    ts_name: 2C - AC Fan / INJ_5
    function: AC Radiator fan
    type: inj

  - pin: 2D
    id: GPIOG_8
    class: outputs
    ts_name: 2D - INJ_2
    function: Injector #2
    type: inj
    color: blue Y1

  - pin: 2E
    id: GPIOC_7
    class: outputs
    ts_name: 2E - COIL_A2 (PWM2)
    function: EGR Valve #1 Coil
    type: ls

  - pin: 2F
    id: GPIOC_6
    class: outputs
    ts_name: 2E - COIL_A1 (PWM1)
    function: EGR Valve #2 Coil
    type: ls

  - pin: 2G
    id: GPIOD_11
    class: outputs
    ts_name: 2G - INJ_3
    function: Injector #3
    type: inj
    color: white Y1

  - pin: 2H
    id: GPIOC_9
    class: outputs
    ts_name: 2H - COIL_B2 (PWM4)
    function: EGR Valve #3 Coil
    type: ls

  - pin: 2I
    id: GPIOC_8
    class: outputs
    ts_name: 2I - COIL_B1 (PWM3)
    function: EGR Valve #4 Coil
    type: ls

  - pin: 2J
    id: GPIOD_10
    class: outputs
    ts_name: 2J - INJ_4
    function: Injector #4
    type: inj
    color: green Y1

  - pin: 2K
    id: GPIOH_15
    class: outputs
    ts_name: 2K - AC (O4)
    function: A/C Relay
    type: ls

  - pin: 2M
    id: GPIOG_2
    class: outputs
    ts_name: 2M - FPUMP (O9)
    function: Fuel Pump Relay
    type: ls
    color: red B4

  - pin: 2N
    id: GPIOF_12
    class: outputs
    ts_name: 2N - VTSC / INJ_6
    function: VTCS Control
    type: inj

  - pin: 2O
    id: GPIOE_4
    class: outputs
    ts_name: 2O - IGN_3
    type: ign

  - pin: 2P
    function: IAC (positive) idle, +12v wired to main relay via 4AF
    color: red, short wire

  - pin: 2Q
    id: GPIOD_14
    class: outputs
    ts_name: 2Q - IDLE (PWM5)
    function: IAC (negative) idle, with diode
    type: ls
    color: blue B4

  - pin: 2R
    id: GPIOG_4
    class: outputs
    ts_name: 2R - CE (O11)
    function: MIL Control
    type: ls
    color: white Y1

  - pin: 3A
    function: Injector GND
    type: gnd
    color: black Y1

  - pin: 3B
    function: PCM (ECU) GND
    type: gnd
    color: black W4, sliced for MAP

  - pin: 3C
    id: GPIOF_13
    class: outputs
    ts_name: 3C - Purge Solenoid / INJ_7
    function: Purge Control Solenoid
    type: inj

  - pin: 3D
    id: GPIOF_14
    class: outputs
    ts_name: 3D - EGR Solenoid / INJ_8
    function: EGR Boost sens. sol.
    type: inj

  - pin: 3E
    id: GPIOG_3
    class: outputs
    ts_name: 3E - CANIST (O10)
    function: CDCV (EVAP canister purge valve) Control
    type: ls

  - pin: 3F
    id: GPIOI_8
    class: outputs
    ts_name: 3F - IGN_1 (1&4)
    function: Coil #1
    type: ign
    color: white B4

  - pin: 3H
    id: GPIOI_2
    class: outputs
    ts_name: 3H - MAIN (O1)
    function: Main relay control
    type: ls
    color: white or red, R5

  - pin: 3I
    id: GPIOE_5
    class: outputs
    ts_name: 3I - IGN_2 (2&3)
    function: Coil #2
    type: ign
    color: orange B4

  - pin: 3J
    id: GPIOH_14
    class: outputs
    ts_name: 3J - O2H (O3)
    function: Front O2 sens. heater GND
    type: ls

  - pin: 3K
    function: NC

  - pin: 3L
    id: GPIOI_6
    class: outputs
    ts_name: 3L - IGN_7 / AFR
    type: ign

  - pin: 3M
    id: GPIOD_15
    class: outputs
    ts_name: 3M - ALTERN (PWM6)
    function: PWM signal to control alternator field voltage
    type: ls
    color: orange R5

  - pin: 3N
    id: GPIOE_3
    class: outputs
    ts_name: 3N - IGN_4
    type: ign

  - pin: 3O
    id: GPIOD_13
    class: outputs
    ts_name: 3O - TACH (PWM7)
    function: Tach Out
    type: ls
    color: green B4

  - pin: 3P
    id: GPIOA_9
    class: outputs
    ts_name: 3P - O2H2 (O7)
    function: Rear O2 sensor heater
    type: ls

  - pin: 3Q
    function: K-Line (serial comm.)

  - pin: 3S
    function: Immobilizer comm.

  - pin: 3T
    id: GPIOF_11
    class: event_inputs
    ts_name: 3T - VSS (D5)
    function: VSS in
    color: blue W3

  - pin: 3U
    id: GPIOH_13
    class: outputs
    ts_name: 3U - AWARN (O2)
    function: Alternator Warning Light
    type: ls

  - pin: 3V
    id: [GPIOA_6, EFI_ADC_6]
    class: [event_inputs, analog_inputs]
    ts_name: 3V - CAM (A19)
    function: Camshaft Sensor
    color: blue W3

  - pin: 3W
    function: NC

  - pin: 3X
    function: NC

  - pin: 3Y
    id: [GPIOB_1, EFI_ADC_9]
    class: [event_inputs, analog_inputs]
    ts_name: 3Y - CRANK (A24)
    function: Crankshaft Sensor
    color: white W3

  - pin: 3Z
    id: GPIOE_2
    class: outputs
    ts_name: 3Z - IGN_5 / GNDA
    type: ign

  - pin: 4A
    function: Ground
    type: gnd
    color: black W4

  - pin: 4B
    id: [GPIOA_1, EFI_ADC_2]
    class: [switch_inputs, analog_inputs]
    ts_name: 4B - Brake/RES1 (A15)
    function: Brake Switch

  - pin: 4C
    id: [GPIOA_3, EFI_ADC_3]
    class: [switch_inputs, analog_inputs]
    ts_name: 4C - Steering/RES2 (A16)
    function: Power Steering Switch

  - pin: 4D
    function: VVT Oil Control Valve pos. +12v wired to main relay via 4AF, short wire

  - pin: 4E
    function: DTM switching (Diagnostic Terminal?)

  - pin: 4F
    id: EFI_ADC_8
    class: analog_inputs
    ts_name: 4F - AC_PRES/AUX1 (A23)
    function: AC Pressure In

  - pin: 4H
    id: [GPIOA_2, EFI_ADC_14]
    class: [switch_inputs, analog_inputs]
    ts_name: 4H - Neutral/AUX2 (A21)
    function: Neutral Switch

  - pin: 4I
    id: [GPIOA_0, EFI_ADC_15]
    class: [switch_inputs, analog_inputs]
    ts_name: 4I - Clutch/AUX3 (A22)
    function: Clutch Switch

  - pin: 4J
    id: EFI_ADC_7
    class: analog_inputs
    ts_name: 4J - VTCS/AUX4 (A20)
    function: VTCS ca. switch

  - pin: 4K
    id: GPIOI_5
    class: outputs
    ts_name: 4K - IGN_6 / +5V_MAP
    type: ign

  - pin: 4L
    function: Sensor +5V
    color: red W3, sliced for MAP

  - pin: 4M
    function: Knock sens. in
    color: white R5

  - pin: 4N
    id: EFI_ADC_1
    class: analog_inputs
    ts_name: 4N - IAT (A14)
    function: IAT sensor
    color: green B2

  - pin: 4O
    function: Sensor GND
    type: gnd
    color: black B2

  - pin: 4P
    id: EFI_ADC_9
    class: analog_inputs
    ts_name: 4P - CLT (A13)
    function: CLT sensor
    color: blue B2

  - pin: 4Q
    function: NC

  - pin: 4R
    id: GPIOI_0
    class: outputs
    ts_name: 4R - VVT (O5)
    function: VVT Oil Control Valve neg.
    type: ls
    color: white B2

  - pin: 4S
    function: +12V engine fuse 15A, ECU power source, run/start
    color: red B2

  - pin: 4T
    function: Alternator output voltage

  - pin: 4U
    id: [GPIOI_7, EFI_ADC_11]
    class: [outputs, analog_inputs]
    ts_name: 4U - MAP2/Ign8 (A10)
    function: NC, extra main relay for diode
    color: red, short wire
    type: ign

  - pin: 4V
    id: EFI_ADC_4
    class: analog_inputs
    ts_name: 4V - TPS (A17)
    function: TPS sensor output
    color: green B2

  - pin: 4W
    id: EFI_ADC_12
    class: analog_inputs
    ts_name: 4W - O2S (A11)
    function: Front O2 Sensor Signal

  - pin: 4X
    id: EFI_ADC_10
    class: analog_inputs
    ts_name: 4X - MAF (A9)
    function: MAF sensor
    color: orange B2

  - pin: 4Z
    function: ECU - TCM, Communication for A/T

  - pin: 4AA
    id: EFI_ADC_13
    class: analog_inputs
    ts_name: 4AA - O2S2 (A12)
    function: Rear O2 Sensor Signal

  - pin: 4AB
    id: EFI_ADC_5
    class: analog_inputs
    ts_name: 4AB - FTP/PPS (A18)
    function: Fuel Tank Pressure Sensor

  - pin: 4AC
    function: ECU - TCM, Communication for A/T

  - pin: 4AD
    function: Fuel Level Sensor

  - pin: 4AE
    function: EGR Boost Pressure Sensor

  - pin: 4AF
    function: +12v from main relay

  - pin: 4AG
    function: Bat+ (Hot all times), 12v 10A fuse from battery

  - pin: 4AH
    function: Evap

