name: Unit Test CI

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Install gcc8
      run: sudo apt-get install -y gcc-8

    - name: Build Tests
      working-directory: ./unit_tests/
      run: make -j8
      
    - name: Run Tests
      run: ./unit_tests/build/rusefi_test
