name: Sync Wiki

on: gollum

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Check out docs repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: rusefi/rusefi_documentation
        persist-credentials: false

    - name: Merge
      run: |
        git remote add best-wiki-git https://github.com/rusefi/rusefi.wiki.git
        git fetch best-wiki-git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git merge best-wiki-git/master

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        repository: rusefi/rusefi_documentation
        github_token: ${{ secrets.ACCESS_TOKEN }}
        branch: master
